[general]
version = "0.1.1"

[problem]
problem_name = "ahc040"
objective = "Min"
score_regex = '(?m)^\s*Score\s*=\s*(?P<score>\d+)\s*$'

[test]
start_seed = 0
end_seed = 100
threads = 0
out_dir = "./pahcer"
compile_steps = []


[[test.test_steps]]
program = "./tester"
args = ["uv", "run", "./py/sample_solution.py"]
stdin = "./pahcer/in/{SEED04}.txt"
stdout = "./pahcer/out/{SEED04}.txt"
stderr = "./pahcer/err/{SEED04}.txt"
measure_time = true
